### ISSUE TITLE
Basic setting instruction and state tracker

### ISSUE THREAD

**Issue by SelfRef** [rozniak/xfce-winxp-tc#305]
Hi Rory,

From time to time I get a message asking how to use this project on Arch Linux. Considering there's much more components than just theme files for XFCE it would be much helpful to have a manual for currently available components. A great example I know is [Chicago95's manual](https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md).

I've noticed that while Xfce standard themes are not often problematic, the `taskband` and other non-standard components are not obvious to enable. That's why I added a simple instruction to [AUR package](https://aur.archlinux.org/pkgbase/xfce-winxp-tc-git#comment-974356) based on my own knowledge to help Arch users at least. I believe generic instructions should work for any distro in case of this project.

The second thing worth adding would be a project state tracker list that shows what features this project already contains (ready to use) and what not (yet ready but in planned).

Here's my draft version from my observations, that you can use :
- Xfce theme
    - [x] Style
        - [x] Windows XP style (blue)
        - [x] Windows Classic style
        - [x] Professional
    - [x] Icons
        - [x] Luna
    - [x] Cursors
        - [x] Windows XP Standard
        - [x] Windows XP Standard (with shadows)
    - [x] Sounds
        - [x] Windows XP Default
- Logon
    - [x] LightDM greeter
    - [ ] Screen locker
- System
    - [ ] Desktop
    - [x] Taskband
    - [x] `winver`
    - [ ] Control Panel
        - [ ] System Properties
        - [ ] Display Properties
        - [ ] Printers
    - [ ] Services
        - [x] Registry
- Applications
    - [x] Explorer
    - [x] Notepad
    - [ ] Paint
    - [ ] Registry Editor

**Comment by SelfRef** [comment]
Well, beneficial or not, the more such a setup will be flexible - the better, I think. Assuming there will be a full "do everything" wizard available, adding an option to run only a part of it won't be a big issue :smiley: 

And in such a case even after installing the package natively, setup will be able to guide a user thought options, styles, etc.

**Comment by rozniak** [comment]
Yeah I would like to consider as much as possible that might vary between distros and such. I definitely haven't got any plans to change how the packages currently work. It's good to have your input about the AUR and stuff, and I'll have a look into the GitHub projects thing when I get a chance. :grin:

**Comment by rozniak** [comment]
Was pondering about instructions etc. yesterday on a walk and I was thinking about perhaps fleshing out some build/install information using the built-in Wiki feature on here. Might be a better, more flexible thing to update than a README. :thinking:

**Comment by SelfRef** [comment]
> ...using the built-in Wiki feature on here...

Definitely good idea. That's where such information should reside, and can be easily updated independently.

Cool fact: Wiki on GitHub is just a separate git repository internally and can be even used through git :smiley:

**Comment by rozniak** [comment]
I've started dabbling with the wiki, such as this page here: https://github.com/rozniak/xfce-winxp-tc/wiki/Install-from-compiled-sources

I'll continue working on it, got to head out now tho :zipper_mouth_face:

**Comment by rozniak** [comment]
Did some more work on it this evening - still dealing with a bit of jet lag so have not done the config stuff yet whilst my brain is a bit frazzled.

I'll tackle the rest tomorrow and the coming days, think main things are what you brought up - config guide (since manual is the only way atm :weary: ) and some information about what exists, the state stuff is in, however I think of to document it. I was thinking perhaps some kind of 'hacking' or 'contributing' guide for poking around individual components if that is useful at all.

**Comment by rozniak** [comment]
@SelfRef Started looking at setup in #250 with some notes regarding AUR :grin:
